# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /blog/:year/:month/:day/:title.html
excerpt_separator: "<!-- more -->"
excerpt_link: "Читать далее"
code_dir: downloads/code
category_dir: categories

# Setup
title:            Fightmaster's blog
tagline:          'A Jekyll theme'
description:      'Скромный персональный блог <a href="https://twitter.com/old_fightmaster" target="_blank">@old_fightmaster</a>'
url:              http://fightmaster.github.io/
baseurl:          /

author:
  name:           'fightmaster'
  url:            https://twitter.com/old_fightmaster

paginate:         5


collections:
    php-lectures:
        output: true
    php-course:
        output: true
    recommendations:
        output: true
    php-lectures-2014-2015:
        output: true
saas:
    style: compressed
    saas_dir: _saas

# Google Analytics
google_analytics_tracking_id: UA-38362255-1

# Disqus Comments
disqus_short_name: fightmaster
disqus_show_comment_count: true


# Twitter
twitter_user: old_fightmaster
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Facebook Like
facebook_like: true