<?php
/**
 * @author Dmitry Petrov <dmitry.petrov@opensoftdev.ru>
 */
class QuickSort implements SortInterface
{
    public function sort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }
}