<?php
/**
 * @author Dmitry Petrov <dmitry.petrov@opensoftdev.ru>
 */
class Sorter
{
    public function quickSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }

    public function shellSort()
    {
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
        //code
    }
}